### ISSUE TITLE
direct pdf/img links to not work with link_thumbnailer?

### ISSUE THREAD

**Issue by BennyOnGit** [gottfrois/link_thumbnailer#105]
Hello there,

This isn't necessarily an issue - more just wondering if this gem is designed to work with .pdf or the varous .png/.jpg/etc links?  

- PDF based links
https://assets.documentcloud.org/documents/277761/united-nations-diplomats-super-pac.pdf
*These PDF's links do not work

-png / jpg based links also do not seem to work
https://i.guim.co.uk/img/media/d29d2a4b1646cec982f068478f7197387cf08b5a/0_95_3500_2100/master/3500.jpg?w=620&q=20&auto=format&usm=12&fit=max&dpr=2&s=8899e8d4bee4b1bcb93d00048742cf00

Lastly, I believe this gem just scrapes existing images from the url, correct?  (Is there no way to create a full screen screenshot similar to what the 'screencap' gem can do?).  

thx,

**Comment by gottfrois** [comment]
Hey!

Thanks for reaching out. As you guessed, the gem is not ready to handle PDF directly. In only handles HTML links. For images, you could use directly the [Image Info](https://github.com/gottfrois/image_info) gem.

> Lastly, I believe this gem just scrapes existing images from the url, correct? (Is there no way to create a full screen screenshot similar to what the 'screencap' gem can do?).

Same here, it does not handle that. The reason is simple, simplicity. Generating a real screenshot of a url can be quite tricky and adds a lot of dependencies.

Hope I answered your questions, feel free to re-open the issue if it is not the case ;)

**Comment by BennyOnGit** [comment]
makes sense - thanks gottfrois.
