### ISSUE TITLE
Any "easy" way to implement "Accept-Language" header?

### ISSUE THREAD

**Issue by rdlh** [gottfrois/link_thumbnailer#142]
Hi !

We're currently using a custom and fixed version of [socialcast/link_preview](https://github.com/socialcast/link_preview).
Is there a way to fetch URLs in a specific language using the "Accept-Language" header with `link_thumbnailer` ?

Cheers

**Comment by gottfrois** [comment]
Hey @rdlh,

Yes it should be pretty straightforward since you can configure the HTTP headers to override on a per-call basis or globally using the built-in configuration option [here](https://github.com/gottfrois/link_thumbnailer/blob/507eff34624ee3e20e865500876439a8d47631c4/lib/link_thumbnailer/configuration.rb#L68):

```ruby
# on a per-call basis
LinkThumbnailer.generate("http://example.com", http_override_headers: { "Accept-Language" => "some value" })

# globally
LinkThumbnailer.configure do |config|
  config.http_override_headers = { "Accept-Language" => "some value" }
end
```
